spring:
  application:
    name: payment

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/instant_payment
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  kafka:
    bootstrap-servers: broker:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer